export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';
export const CUSTOMER_ORDER_LIST = 'CUSTOMER_ORDER_LIST';
export const CUSTOMER_EXPIRED_LIST = 'CUSTOMER_EXPIRED_LIST';
export const GET_ALL_WAREHOUSE = 'GET_ALL_WAREHOUSE';
export const GET_CUSTOMER_INVOICE = 'GET_CUSTOMER_INVOICE';
